### ISSUE TITLE
Related Posts affected by files all saved with -title slug

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#55]
On a page such as [Material Organization Refactoring](http://teach.github.com/articles/Refactoring/) the Related Posts section only has one working link.

The others all point to:

```
http://teach.github.com/articles/title
```

Looks like fallout from posts using the same `-title` slug end like:

```
0002-01-01-title.md
```

Where otherwise it would benefit with a unique slug to help create the hyperlinks.

```
0002-01-01-pull-vs-fetch.md
```

**Comment by matthewmccullough** [comment]
You are so right.  I'll try to hit those up along with some @github/training-team members.

**Comment by matthewmccullough** [comment]
There are still a few more slide to rename.

**Comment by matthewmccullough** [comment]
@jordanmccullough I think I need some help here to filter out slides from appearing in the recommended links, if there's even a way to do that.

**Comment by jordanmccullough** [comment]
Did some hacking on this yesterday, and hit a blocker with some Jekyll weirdness. Might need to chat with an expert in Liquid and Jekyll to resolve.

**Comment by matthewmccullough** [comment]
Calling an awesome @cobyism for Jekyll help.  @jordanmccullough can you recap for Coby what the barrier is here in a nutshell?

**Comment by cobyism** [comment]
@jordanmccullough Happy to try and help :grinning: —what kind of stuff did you run into, exactly?

**Comment by jordanmccullough** [comment]
@cobyism, thank for offering to help.

For the teach.github.com "presentations" slide deck HTML files, we've put a front matter of `categories: ['presentations']`. With the /presentations/index.md using the Jekyll include `categorycontents`, we're seeing all _posts included in the output, not just the Markdown files with the category `presentations` front matter.

Clearly I'm totally overlooking something here, but any insight would be appreciated.

**Comment by cobyism** [comment]
@jordanmccullough  Ok, I’m pretty sure I know why you’re seeing this.

The way Jekyll works is that categories are derived from the directory structure above the `_posts` directory. For example, a post located at `/work/code/_posts/2008-12-24-closures.textile` would have this field automatically set to `['work', 'code']` (without setting it in the YAML front-matter. They can _also_ be specified in the front-matter, but the inheritance from the directory structure is likely what is causing your problem here.

Basically, because you have a `_posts` directory underneath a `/presentations` directory, this means any markdown file in that `/presentations/_posts` folder will inherit a categories value of `['presentations']` **whether you specify it in the YAML front-matter or not**.

There’s a couple of ways you could get around this:
1. Alter the directory structure so the inherited category and the YAML-specified category are not the same.
2. Alter the YAML-specified category to be different from the directory-inherited category name.
3. Add a secondary, arbitrary category name to the YAML front-matter for posts you want to show up, and make that the one you specify in the `{% assign selectedcategory = ... %}` line of `index.md`.

I’d probably recommend option 2, with changing the YAML-specified category to maybe be just `['presentation']` (no 's', singular) since that’s what that specific file represents so it makes a little bit of sense—or possibly option 3. Option 1 would suck because it would necessarily affect the URL structure, and I’m guessing that’s not ideal.

I hope that helps you troubleshoot? Let me know if there’s anything I can do (or clarify further) to help get things working as you want them to and I can have a dig :smile:

**Comment by brntbeer** [comment]
Link to #66 as a related issue.

**Comment by jordanmccullough** [comment]
@brntbeer Thanks for associating these two issues. Looking into these and should have word on them tomorrow (03/13/13).

**Comment by jordanmccullough** [comment]
Almost done with a major refactor. All markdown files will have the title embedded, no Front Matter "title" attribute requirement, etc. The HydeSlides control panel will now show like so...

![PastedGraphic-1](https://f.cloud.github.com/assets/352082/256969/9127495e-8c3e-11e2-9df2-3cf3dca72f37.png)

**Comment by brntbeer** [comment]
This is so awesome. happy to see progress updates!

**Comment by cobyism** [comment]
Woah, nice!

**Comment by matthewmccullough** [comment]
I sure do love the new control panel and titles to all the slides!  This came in via https://github.com/github/teach.github.com/pull/91

However, they still show up on http://teach.github.com/presentations/ when they shouldn't (category assignment to cause them not to show?). I'm going to try and hack on that right now.

**Comment by jordanmccullough** [comment]
Slipped from my schedule yesterday, but trying to tackle this following the title fixes. @cobyism provided some insight and tips, and I'm sure if I just apply the suggested changes, things will clear up.

**Comment by matthewmccullough** [comment]
@cobyism I tried your option 2, but it didn't seem to work. See http://teach.github.com/presentations/ for pages still showing up that have had their category explicitly assigned to be something other than `presentations`.  As a fall back, I think I'll try shifting the "loop" to use another category and then just assigning the pages I want to show up to use that "special" category.  That would be more DRY as well.

**Comment by cobyism** [comment]
@matthewmccullough Bummer, it may be the case that it’s impossible to _override_ the inherited categories, and that instead any YAML-specified categories are merely _added_ to the existing set generated from the directory structure.

**Comment by jordanmccullough** [comment]
Closing this down following the [migration effort](https://github.com/github/teach.github.com/pull/244) and the [data restructuring](https://github.com/github/training.github.com/pull/156) of all combined training.github.com/teach.github.com content.
