### ISSUE TITLE
Links to presentations are broken

### ISSUE THREAD

**Issue by foca** [github/teach.github.com#66]
Every link in http://teach.github.com/presentations/ takes me to http://teach.github.com/articles/title/, which has nothing.

**Comment by matthewmccullough** [comment]
Nice catch.  It was on the TODO list, but I'm finally fixing it now.  What happened is that all the HydeSlides in the presentations `_posts` subfolder are showing up as articles but should not.  The fix is to put: `categories: ['slidecontent']` in the frontmatter so that the category selector on https://github.com/github/teach.github.com/blob/gh-pages/presentations/index.md doesn't pick them up.

**Comment by brntbeer** [comment]
ahhhh i love this! Awesome fix @matthewmccullough and find @foca !

**Comment by foca** [comment]
:boom: :zap: :heart:

**Comment by matthewmccullough** [comment]
Still has some flaws in the current fix.  Reviewing this with @brntbeer tomorrow.

**Comment by brntbeer** [comment]
Gasp. :triumph: lets do this.

**Comment by brntbeer** [comment]
Isnt an issue anymore. our index is actually an index now!
