### ISSUE TITLE
Order logic on Class Notes list

### ISSUE THREAD

**Issue by randomecho** [github/teach.github.com#76]
Is there an order being used on the [List of Class Notes](http://teach.github.com/classnotes/) display? Or is it just a quirk of the generator?

The first five on the list:
- 2013-02-21 • GNM Private Advanced Class
- 2013-01-10 • Online Git Advanced Class
- 2012-10-31 • Git and GitHub Foundations Online
- 2013-02-11 • GitHub Foundations
- 2013-02-18 • Git and GitHub Foundations Online

The dates are a little all over the place.

**Comment by matthewmccullough** [comment]
So incredibly frustrating. I've attempted to use all methods of sorting (they work locally on my machine) and none of them seem to take effect on the server side.  I even just attempted a Liquid sort criteria.  Had no effect.  What in the world is going on? Help!

**Comment by brntbeer** [comment]
yeah it looks like our sortby on the forloop should work but it doesnt :( agree at frustration.

**Comment by matthewmccullough** [comment]
@cobyism Any insights here? Driven crazy by inability to sort the elements on this page. They literally look random.

**Comment by cobyism** [comment]
The dates themselves should be doing the sorting just fine (otherwise this would be a problem for approximately everyone who uses Jekyll), so I have no idea why there is a discrepancy between the order generated locally and the order generated on the gh-pages server. @jch Do you have any idea why this might be the case?

As far as [the sort syntax being used for the index page in question](https://github.com/github/teach.github.com/blame/gh-pages/classnotes/index.md#L10) though, to the best of my knowledge it doesn’t **actually exist** in Liquid proper. There’s a pull request that adds it at Shopify/liquid#101, but it looks like that’s not been merged (see also mojombo/jekyll#766).

**Comment by cobyism** [comment]
One factor that might be in play here is the use of the `site.html_pages` hash (as opposed to having everything in `/classnotes/_posts` and using `site.categories.classnotes` hash) to access the list—maybe that’s where the screwy order is coming from? @matthewmccullough Have you tried moving `/classnotes/*` (except the `index.md`) into `/classnotes/_posts/*` and then doing the loop like:

``` html
<ul>
  {% for post in site.categories.classnotes reversed %}
      <li>…</li>
  {% endfor %}
</ul>
```

`v0v`

**Comment by jch** [comment]
Sorry, but I actually don't know anything about Jekyll. Not sure how that rumor got started heh. 
—
Jerry Cheung
GitHub Enterprise Engineer

**Comment by matthewmccullough** [comment]
Locally, it sorts just fine:

![Screen Shot 2013-03-16 at 4 32 58 PM](https://f.cloud.github.com/assets/24734/267468/91703e6e-8e89-11e2-96e1-f356ddea9bc9.jpg)

Remotely at http://teach.github.com/classnotes/, I can't decipher what the ordering is controlled by.

![Screen Shot 2013-03-16 at 4 34 32 PM](https://f.cloud.github.com/assets/24734/267470/b8ad8e46-8e89-11e2-867f-682e8802b5e7.jpg)

**Comment by matthewmccullough** [comment]
@cobyism your tactic works, but that's going to be a bit of a hassle to convert and maintain; I think I'd need to set the `permalink` on each and every one of the new pages so that it rendered at the old URL, right?  Or at least put in JS redirect for all the old pages to point to the new locations.

I implemented a draft first step of this approach you suggested: https://github.com/github/teach.github.com/pull/97

**Comment by matthewmccullough** [comment]
We have some modestly labor-intensive workarounds that work, but I'm wondering if I can call upon you @parkr to throw any light on the sort order problem I'm seeing in the above screenshots and to see if he has any last minute tips besides the workaround that @cobyism suggested (that works, but requires band-aiding the old URLs).

Recap: Locally, the [category iterator](https://github.com/github/teach.github.com/blame/gh-pages/classnotes/index.md#L10) sorts by filename/date.  On GitHub, it sorts in an unknown order. Anything I'm mis-using with Jekyll that is causing this sorting to be different on GitHub than locally-run Jekyll v0.12.1, @parkr?

**Comment by matthewmccullough** [comment]
We internally discussed this and we don't want to present the global list of class notes to future students.  We'd like to make it intimate in that each class gets their link, but doesn't have to wade through others.  The teaching materials should be a great reference for all students moreso than browsing other classes' class notes.

**Comment by matthewmccullough** [comment]
CC: @jordanmccullough

**Comment by randomecho** [comment]
That whole chunk between the presenter details and log & transcript could probably also be whisked away to a single point to avoid repeating that section every time.

**Comment by jordanmccullough** [comment]
@randomecho: I have a yet-to-be-PRed effort underway to template the Class Notes so that the resource links, training information, etc. are all external Markdown files from the class-specific content. 

If I understand correctly, that's also what your'e suggesting in the "avoid repeating" comment and I totally dig that idea. :+1:

**Comment by randomecho** [comment]
@jordanmccullough Yes, actually. Saw something like `{include:file:LICENSE.md}` on some other repo a while back where it dropped in the file on the live render. Forgot about it until watching the consolidation going on here.

**Comment by jordanmccullough** [comment]
The modular classnotes effort is now happening here: https://github.com/github/training.github.com/pull/149
